name: Build and publish

on:
  push:
    branches: [ main ]

jobs:
  TestBuildAndPush:
    runs-on: ubuntu-latest
    name: Test, Build and Push the Microservice
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push API Server
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ghcr.io/wa2g07/simple-service:${{ github.sha }}
